name = "email-signature-api"
main = "workers/index.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
    { binding = "USERS", id = "9de39def74474a1e8358b774a46f27d5" },
    { binding = "SIGNATURES", id = "f1017b7b13c04a178234432e35d077e5" }
]

[vars]
JWT_SECRET = "iyYCEL0SOlmPr5b06a1tQutvJ6vGWToiONelu..."

[env.production]
name = "email-signature-api"
main = "workers/index.js"
kv_namespaces = [
    { binding = "USERS", id = "9de39def74474a1e8358b774a46f27d5" },
    { binding = "SIGNATURES", id = "f1017b7b13c04a178234432e35d077e5" }
]

[env.clear-kv]
name = "clear-kv"
main = "workers/clear-kv.js"
kv_namespaces = [
    { binding = "USERS", id = "9de39def74474a1e8358b774a46f27d5" },
    { binding = "SIGNATURES", id = "f1017b7b13c04a178234432e35d077e5" }
]
